version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:14.4
    environment:
      - POSTGRES_PASSWORD=chat_pass
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/:rw
      - ./scripts/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
      - ./scripts/postgres_always.sh:/postgres_always.sh:ro
      - ./scripts/postgres_run.sh:/usr/local/bin/postgres_run.sh:ro
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "psql -U chat_user -d chat_db -c 'SELECT 1;'"]
      interval: 60s
      timeout: 5s
      retries: 3
    command: postgres_run.sh
